version: '3.7'
services:
    sonarqube:
        image: sonarqube
        container_name: sonarqube
        networks:
        - tlog
        ports:
        - "9000:9000"
        - "9092:9092"
networks:
    tlog: